language: java
install: true

script:
- mvn checkstyle:check
- mvn checkstyle:checkstyle
- mvn checkstyle:checkstyle-aggregate
- mvn jacoco:report
- mvn jacoco:report-aggregate
- mvn verify
- mvn compile
- mvn test
- mvn jar:jar
- mvn jar:test-jar
- mvn source:jar
- mvn source:test-jar
- mvn process-sources
- mvn process-classes
- mvn surefire:test
- mvn clean package
- mvn clean install
jdk:
  - oraclejdk8
